name: Poll Firebase Every 10 Seconds

on:
  schedule:
    - cron: "*/1 * * * *" # Runs every minute
    workflow_dispatch:

jobs:
  poll:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Function
        run: |
          for i in {1..6}; do
            curl -X GET "https://lhdhuonairkdxzpaaqpi.supabase.co/functions/v1/monitor-firebase" \
              -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"
            sleep 10
          done
